; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
upload_port = /dev/ttyUSB0
upload_speed = 921600
monitor_port = /dev/ttyUSB0
monitor_speed = 115200

build_src_filter =
    -<**>

[arduino]
framework = arduino

[esp8266]
extends=arduino
platform = espressif8266
upload_speed = 921600

[esp32]
extends=arduino
platform = espressif32

[esp32s3]
extends=esp32
# USB CDC
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0

[hw:seeed-xiao-esp32s3-plus]
extends=esp32s3
board = seeed_xiao_esp32s3
build_flags =
    -DBUILTIN_LED_PIN=21
    -DNATIVE_USB=1
    -DBUILTIN_LED_PIN_MODE=OUTPUT_OPEN_DRAIN
    -DHW_I2C_PIN_SDA=5
    -DHW_I2C_PIN_SCL=6

[hw:esp32dev]
extends=esp32
board = esp32dev
build_flags =
    -DBUILTIN_LED_PIN=21
    -DBUILTIN_LED_PIN_MODE=OUTPUT_OPEN_DRAIN
    -DHW_I2C_PIN_SDA=5
    -DHW_I2C_PIN_SCL=6

[hw:wemos-d1-mini]
extends=esp8266
board = d1_mini
build_flags =
    -DBUILTIN_LED_PIN=2
    -DBUILTIN_LED_PIN_MODE=OUTPUT
    -DHW_I2C_PIN_SDA=5
    -DHW_I2C_PIN_SCL=4

[hw:default]
extends=hw:wemos-d1-mini
# extends=hw:seeed-xiao-esp32s3-plus

[hw:default-esp32]
extends=hw:esp32dev

[hw:default-esp32s3]
extends=hw:seeed-xiao-esp32s3-plus

[env:hello-world]
extends=hw:default
build_src_filter =
	${env.build_src_filter}
	+<hello-world/**>

[env:hello-world-esp32]
extends=esp32, env:hello-world

[env:hello-world-esp32s3]
extends=esp32s3, env:hello-world

[env:gpio]
extends=hw:default
build_src_filter =
	${env.build_src_filter}
	+<gpio/**>

[env:mcp23017-demo]
extends=hw:default
build_src_filter =
	${env.build_src_filter}
	+<mcp23017-demo/**>

[env:logic-analyzer]
extends=hw:default
build_src_filter =
	${env.build_src_filter}
	+<logic-analyzer/**>

[env:logic-analyzer-debug]
extends=env:logic-analyzer

build_flags =
    ${env:logic-analyzer.build_flags}
    -DDEBUG_PROTOCOL=1

[env:leds]
extends=hw:default
build_src_filter =
	${env.build_src_filter}
	+<leds/**>

[env:i2c-scanner]
extends=hw:default
build_src_filter =
	${env.build_src_filter}
	+<i2c-scanner/**>

[env:mpu6050-demo]
extends=hw:default
; Define the device ID for Fake MPU6050
; 0x68 = genuine MPU6050
; 0x98 = some MPU6050 clones
build_flags = -DMPU6050_DEVICE_ID=0x98
build_src_filter =
       ${env.build_src_filter}
       +<mpu6050-demo/**>

[env:function-generator]
; The application uses HW DAC, so it is limited to esp32.
; esp32s3 does not have DAC
extends=hw:esp32dev
build_src_filter =
       ${env.build_src_filter}
       +<function-generator/**>
